<!doctype html>
<html class="no-js " lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <link rel="stylesheet" href="dashboard/assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="dashboard/assets/plugins/jvectormap/jquery-jvectormap-2.0.3.min.css" />
    <link rel="stylesheet" href="dashboard/assets/plugins/charts-c3/plugin.css" />
    <link rel="stylesheet" href="dashboard/assets/plugins/morrisjs/morris.min.css" />
    <link rel="stylesheet" href="dashboard/assets/css/style.min.css">
    <link rel="stylesheet" href="dashboard/assets/plugins/footable-bootstrap/css/footable.bootstrap.min.css">
    <link rel="stylesheet" href="dashboard/assets/plugins/footable-bootstrap/css/footable.standalone.min.css">
    <link rel="stylesheet" href="dashboard/assets/plugins/summernote/dist/summernote.css" />
    <link rel="stylesheet" href="dashboard/assets/plugins/bootstrap-select/css/bootstrap-select.css" />
    <!-- Custom Css -->

    <script src="dashboard/assets/bundles/libscripts.bundle.js"></script>
    <script src="dashboard/assets/bundles/vendorscripts.bundle.js"></script>
    <script src="dashboard/assets/bundles/jvectormap.bundle.js"></script>
    <script src="dashboard/assets/bundles/sparkline.bundle.js"></script>
    <script src="dashboard/assets/bundles/c3.bundle.js"></script>
    <script src="dashboard/assets/bundles/mainscripts.bundle.js"></script>
    <script src="dashboard/assets/js/pages/index.js"></script>

    <!-- contact Js -->
    <script src="dashboard/assets/bundles/footable.bundle.js"></script>
    <script src="dashboard/assets/js/pages/tables/footable.js"></script>

    <!-- Blog Dash Js -->
    <script src="dashboard/assets/plugins/jvectormap/jquery-jvectormap-us-aea-en.js"></script>
    <script src="dashboard/assets/js/pages/blog/blog.js"></script>

    <!--  Blog Post Js -->
    <script src="dashboard/assets/plugins/dropzone/dropzone.js"></script>
    <script src="dashboard/assets/plugins/summernote/dist/summernote.js"></script>

    <!-- Ecommerce dash Js -->
    <script src="dashboard/assets/bundles/morrisscripts.bundle.js"></script>
    <script src="dashboard/assets/bundles/knob.bundle.js"></script>
    <script src="dashboard/assets/js/pages/ecommerce.js"></script>
    <script src="dashboard/assets/js/pages/charts/jquery-knob.min.js"></script>
</head>