<footer id="footer" class="footer">

  <div class="footer-content">
    <div class="container">

      <div class="row g-5">
        <div class="col-lg-4">
          <h3 class="footer-heading">About Bytes</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam ab,
            perspiciatis beatae autem deleniti voluptate nulla a dolores, exercitationem
            eveniet libero laudantium recusandae officiis qui aliquid blanditiis omnis quae. Explicabo?
          </p>
          <p><a href="/about" class="footer-link-more">Learn More</a></p>
        </div>
        <div class="col-6 col-lg-2">
          <h3 class="footer-heading">Navigation</h3>
          <ul class="footer-links list-unstyled">
            <li><a href="/"><i class="bi bi-chevron-right"></i> Home</a></li>
            <li><a href="/category"><i class="bi bi-chevron-right"></i> Categories</a></li>
            <li><a href="/about"><i class="bi bi-chevron-right"></i> About me</a></li>
            <li><a href="/contact"><i class="bi bi-chevron-right"></i> Contact</a></li>
          </ul>
        </div>
        <div class="col-6 col-lg-2">
          <h3 class="footer-heading">Categories</h3>
          <ul class="footer-links list-unstyled">
            <li><a href="/category"><i class="bi bi-chevron-right"></i> Business</a></li>
            <li><a href="/category"><i class="bi bi-chevron-right"></i> Culture</a></li>
            <li><a href="/category"><i class="bi bi-chevron-right"></i> Sport</a></li>
            <li><a href="/category"><i class="bi bi-chevron-right"></i> Politics</a></li>

          </ul>
        </div>

        <div class="col-lg-4">
          <h3 class="footer-heading">Recent Posts</h3>

          <ul class="footer-links footer-blog-entry list-unstyled">
            <li>
              <a href="/post" class="d-flex align-items-center">
                <img style="border-radius: 5px;" src="assets/img/post-sq-1.jpg" alt="" class="img-fluid me-3">
                <div>
                  <div class="post-meta d-block"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                  <span>5 Great Startup Tips for Female Founders</span>
                </div>
              </a>
            </li>

            <li>
              <a href="/post" class="d-flex align-items-center">
                <img style="border-radius: 5px;" src="assets/img/post-sq-2.jpg" alt="" class="img-fluid me-3">
                <div>
                  <div class="post-meta d-block"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                  <span>What is the son of Football Coach John Gruden, Deuce Gruden doing Now?</span>
                </div>
              </a>
            </li>
          </ul>

        </div>
      </div>
    </div>
  </div>

  <div class="footer-legal">
    <div class="container">

      <div class="row justify-content-between">
        <div class="col-md-4 text-center text-md-start mb-3 mb-md-0">
          <div class="copyright">
            © Copyright <strong><span>ZenBlog</span></strong>. All Rights Reserved
          </div>
        </div>

        <div class="col-md-4 text-center text-md-start mb-3 mb-md-0">
          <div class="credits">
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
          </div>

          <div class="credits">
            Updated by <a href="https://github.com/programmingChiira">Dennis Chiira</a>
          </div>

        </div>

        <div class="col-md-4">
          <div class="social-links mb-3 mb-lg-0 text-center text-md-end">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="google-plus"><i class="bi bi-skype"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>

        </div>

      </div>

    </div>
  </div>

</footer>
<!-- Navbar -->