<head>
  <style>
    #activelink {
      color: #179482;
    }
  </style>
</head>
<header id="header" class="header d-flex align-items-center fixed-top">
  <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

    <a href="/" class="logo d-flex align-items-center">
      <!-- Uncomment the line below if you also wish to use an image logo -->
      <img style="border-radius: 5px;" src="assets/img/logo.png" alt="">
      <h1>WhimsyWords</h1>
    </a>

    <nav id="navbar" class="navbar">
      <ul>
        <li><a <?php echo ($_SERVER['REQUEST_URI'] == '/') ? 'id="activelink"' : ''; ?> href="/">Home</a></li>
        <li><a <?php echo ($_SERVER['REQUEST_URI'] == '/about') ? 'id="activelink"' : ''; ?> href="/about">About Us</a></li>
        <li class="dropdown">
          <a <?php echo ($_SERVER['REQUEST_URI'] == '/category') ||
                ($_SERVER['REQUEST_URI'] == '/category') ||
                ($_SERVER['REQUEST_URI'] == '/category') ||
                ($_SERVER['REQUEST_URI'] == '/category') ||
                ($_SERVER['REQUEST_URI'] == '/category')
                ? 'id="activelink"' : '';
              ?> href="/category"><span>Categories</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
          <ul>
            <li><a <?php echo ($_SERVER['REQUEST_URI'] == '/category') ? 'id="activelink"' : ''; ?> href="/category">Drop Down 1</a></li>
            <li><a <?php echo ($_SERVER['REQUEST_URI'] == '/category') ? 'id="activelink"' : ''; ?> href="/category">Drop Down 2</a></li>
            <li><a <?php echo ($_SERVER['REQUEST_URI'] == '/category') ? 'id="activelink"' : ''; ?> href="/category">Drop Down 3</a></li>
            <li><a <?php echo ($_SERVER['REQUEST_URI'] == '/category') ? 'id="activelink"' : ''; ?> href="/category">Drop Down 4</a></li>
            <li><a <?php echo ($_SERVER['REQUEST_URI'] == '/category') ? 'id="activelink"' : ''; ?> href="/category">Drop Down 5</a></li>
          </ul>
        </li>


        <li><a <?php echo ($_SERVER['REQUEST_URI'] == '/contact') ? 'id="activelink"' : ''; ?> href="/contact">Contact</a></li>
      </ul>
    </nav><!-- .navbar -->

    <div class="position-relative">
      <a href="#" class="mx-2"><span class="bi-facebook"></span></a>
      <a href="#" class="mx-2"><span class="bi-twitter"></span></a>
      <a href="#" class="mx-2"><span class="bi-instagram"></span></a>

      <a href="#" class="mx-2 js-search-open"><span class="bi-search"></span></a>
      <i class="bi bi-list mobile-nav-toggle"></i>

      <!-- ======= Search Form ======= -->
      <div class="search-form-wrap js-search-form-wrap">
        <form action="/search" class="search-form">
          <span class="icon bi-search"></span>
          <input type="text" placeholder="Search" class="form-control">
          <button class="btn js-search-close"><span class="bi-x"></span></button>
        </form>
      </div><!-- End Search Form -->

    </div>

  </div>

</header>
<!-- Navbar -->