<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document Files :- Bytes</title>
    <meta name="description" content="Page description">
    <meta name="keywords" content="about, company, team">
</head>
<?php $this->partial('partials/dash-meta'); ?>
<?php $this->partial('partials/dash-navigation'); ?>

<body class="theme-blush">
    <section class="content file_manager">
        <div class="body_scroll">
            <div class="block-header">
                <div class="row">
                    <div class="col-lg-7 col-md-6 col-sm-12">
                        <h2>Documents</h2>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/authDashboard"><i class="zmdi zmdi-home"></i> Byte</a></li>
                            <li class="breadcrumb-item"><a href="file-dashboard.html">File Manager</a></li>
                            <li class="breadcrumb-item active">Documents</li>
                        </ul>
                        <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
                    </div>
                    <div class="col-lg-5 col-md-6 col-sm-12">
                        <button class="btn btn-primary btn-icon float-right right_icon_toggle_btn" type="button"><i class="zmdi zmdi-arrow-right"></i></button>
                        <button class="btn btn-success btn-icon float-right" type="button"><i class="zmdi zmdi-upload"></i></button>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12">
                        <div class="card">
                            <ul class="nav nav-tabs pl-0 pr-0">
                                <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#doc">Doc</a></li>
                                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#pdf">PDF</a></li>
                                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#xls">XLS</a></li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane active" id="doc">
                                    <div class="row clearfix">
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-file-text"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Document_2019.doc</p>
                                                            <small>Size: 42KB <span class="date text-muted">Nov 02, 2019</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-file-text"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Document_2019.doc</p>
                                                            <small>Size: 89KB <span class="date text-muted">Dec 15, 2019</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-file-text"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Document_2019.doc</p>
                                                            <small>Size: 89KB <span class="date text-muted">Dec 15, 2019</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-file-text"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Document_2019.doc</p>
                                                            <small>Size: 42KB <span class="date text-muted">Nov 02, 2019</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-file-text"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Document_2019.doc</p>
                                                            <small>Size: 89KB <span class="date text-muted">Dec 15, 2019</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-file-text"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Document_2019.doc</p>
                                                            <small>Size: 89KB <span class="date text-muted">Dec 15, 2019</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane" id="pdf">
                                    <div class="row clearfix">
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-collection-pdf"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">asdf hhkj.pdf</p>
                                                            <small>Size: 3MB <span class="date text-muted">Aug 18, 2019</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-collection-pdf"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">asdf hhkj.pdf</p>
                                                            <small>Size: 3MB <span class="date text-muted">Aug 18, 2019</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-collection-pdf"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">asdf hhkj.pdf</p>
                                                            <small>Size: 3MB <span class="date text-muted">Aug 18, 2019</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-collection-pdf"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">asdf hhkj.pdf</p>
                                                            <small>Size: 3MB <span class="date text-muted">Aug 18, 2019</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane" id="xls">
                                    <div class="row clearfix">
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-chart"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Report2016.xls</p>
                                                            <small>Size: 68KB <span class="date text-muted">Dec 12, 2016</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-chart"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Report2019.xls</p>
                                                            <small>Size: 103KB <span class="date text-muted">Jan 24, 2016</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-chart"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Report2016.xls</p>
                                                            <small>Size: 68KB <span class="date text-muted">Dec 12, 2016</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-chart"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Report2016.xls</p>
                                                            <small>Size: 68KB <span class="date text-muted">Dec 12, 2016</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-chart"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Report2019.xls</p>
                                                            <small>Size: 103KB <span class="date text-muted">Jan 24, 2016</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-chart"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Report2016.xls</p>
                                                            <small>Size: 68KB <span class="date text-muted">Dec 12, 2016</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-chart"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Report2016.xls</p>
                                                            <small>Size: 68KB <span class="date text-muted">Dec 12, 2016</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-chart"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Report2019.xls</p>
                                                            <small>Size: 103KB <span class="date text-muted">Jan 24, 2016</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <a href="javascript:void(0);">
                                                        <div class="hover">
                                                            <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="zmdi zmdi-chart"></i>
                                                        </div>
                                                        <div class="file-name">
                                                            <p class="m-b-5 text-muted">Report2016.xls</p>
                                                            <small>Size: 68KB <span class="date text-muted">Dec 12, 2016</span></small>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>