<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Editor :- Bytes</title>
    <meta name="description" content="Page description">
    <meta name="keywords" content="about, company, team">
</head>
<?php $this->partial('partials/dash-meta'); ?>
<?php $this->partial('partials/dash-navigation'); ?>

<body class="theme-blush">
    <section class="content blog-page">
        <div class="body_scroll">
            <div class="block-header">
                <div class="row">
                    <div class="col-lg-7 col-md-6 col-sm-12">
                        <h2>Blog Post</h2>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i> Aero</a></li>
                            <li class="breadcrumb-item"><a href="blog-dashboard.html">Blog</a></li>
                            <li class="breadcrumb-item active">New Post</li>
                        </ul>
                        <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
                    </div>
                    <div class="col-lg-5 col-md-6 col-sm-12">
                        <button class="btn btn-primary btn-icon float-right right_icon_toggle_btn" type="button"><i class="zmdi zmdi-arrow-right"></i></button>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="body">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Enter Blog title" />
                                </div>
                                <select class="form-control show-tick">
                                    <option>Select Category --</option>
                                    <option>Web Design</option>
                                    <option>Photography</option>
                                    <option>Technology</option>
                                    <option>Lifestyle</option>
                                    <option>Sports</option>
                                </select>
                            </div>
                        </div>
                        <div class="card">
                            <div class="body">
                                <div class="summernote">
                                    Hello there,
                                    <br />
                                    <p>The toolbar can be customized and it also supports various callbacks such as <code>oninit</code>, <code>onfocus</code>, <code>onpaste</code> and many more.</p>
                                    <p>Please try <b>paste some texts</b> here</p>
                                </div>
                                <button type="button" class="btn btn-info waves-effect m-t-20">POST</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>